name: General Issue
description: Report a general issue or ask a question about the C++ build tools
title: "[Issue]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reaching out! Please provide as much detail as possible.
  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      description: What type of issue is this?
      options:
        - Question
        - Documentation
        - Build/Configuration Issue
        - Tool Request
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe your issue or question in detail.
      placeholder: A clear and concise description of what you need help with.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context, such as your build environment, tools being used, or specific requirements.
      placeholder: Tell us about your setup and what you're trying to accomplish.
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Add any other relevant information, logs, or examples.
  - type: dropdown
    attributes:
      label: Tip
      description: This element is static, used to render a helpful sub-heading for end-users and community members to help prioritize issues. Please leave as is.
      options:
        - <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
      default: 0